config/routes.rb
Rails.application.routes.draw do
  resources :games
  resources :leagues
  resources :teams

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  belongs_to :game
  belongs_to :team
end

app/models/game.rb
class Game < ActiveRecord::Base
	mount_uploader :featured_photo, ImageUploader
	
	#associations
	has_many :features
	has_many :teams, through: :features
end

app/models/league.rb
class League < ActiveRecord::Base
	mount_uploader :logo, ImageUploader
end

app/models/team.rb
class Team < ActiveRecord::Base
	mount_uploader :logo, ImageUploader
	
	#associations
	has_many :features
	has_many :games, through: :features
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:team_1, :team_1_news, :team_2, :team_2_news, :match_details, :featured_photo, :game_prediciton, :reason_for_bet_tip, :head_to_head, :stat, { :team_ids => [] } )
    end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:title, :logo)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :logo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/_form.html.erb
<%= form_for @game, html: { multipart: true } do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :match_details %><br>
    <%= f.text_area :match_details %>
  </div>
  <div class="field">
    <%= f.label :featured_photo %><br>
    <%= f.file_field :featured_photo %>
  </div>
  <div class="field">
    <%= f.label :game_prediciton %><br>
    <%= f.text_field :game_prediciton %>
  </div>
  <div class="field">
    <%= f.label :reason_for_bet_tip %><br>
    <%= f.text_area :reason_for_bet_tip %>
  </div>
  <div class="field">
    <%= f.label :head_to_head %><br>
    <%= f.text_area :head_to_head %>
  </div>
  <div class="field">
    <%= f.label :stat %><br>
    <%= f.text_field :stat %>
  </div>

  <h3>Select teams for this game.</h3>
  <div class="field">
    <%= f.label :employer_ids %><br />
    <%= collection_check_boxes(:game, :team_ids, Team.all, :id, :name) %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Team 1</th>
      <th>Team 1 news</th>
      <th>Team 2</th>
      <th>Team 2 news</th>
      <th>Match details</th>
      <th>Featured photo</th>
      <th>Game prediciton</th>
      <th>Reason for bet tip</th>
      <th>Head to head</th>
      <th>Stat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.team_1 %></td>
        <td><%= game.team_1_news %></td>
        <td><%= game.team_2 %></td>
        <td><%= game.team_2_news %></td>
        <td><%= game.match_details %></td>
        <td><%= game.featured_photo %></td>
        <td><%= game.game_prediciton %></td>
        <td><%= game.reason_for_bet_tip %></td>
        <td><%= game.head_to_head %></td>
        <td><%= game.stat %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team 1:</strong>
  <%= @game.team_1 %>
</p>

<p>
  <strong>Team 1 news:</strong>
  <%= @game.team_1_news %>
</p>

<p>
  <strong>Team 2:</strong>
  <%= @game.team_2 %>
</p>

<p>
  <strong>Team 2 news:</strong>
  <%= @game.team_2_news %>
</p>

<p>
  <strong>Match details:</strong>
  <%= @game.match_details %>
</p>

<p>
  <strong>Featured photo:</strong>
  <%= image_tag @game.featured_photo_url %>
</p>

<p>
  <strong>Game prediciton:</strong>
  <%= @game.game_prediciton %>
</p>

<p>
  <strong>Reason for bet tip:</strong>
  <%= @game.reason_for_bet_tip %>
</p>

<p>
  <strong>Head to head:</strong>
  <%= @game.head_to_head %>
</p>

<p>
  <strong>Stat:</strong>
  <%= @game.stat %>
</p>


<h2> Team playing this game</h2>

<h4><%=link_to @game.teams.first.name, team_path(@game.teams.first)  %> vs <%= link_to @game.teams.last.name, team_path(@game.teams.last) %></h4>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soccerbetexperts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leagues/_form.html.erb
<%= form_for @league, html: { multipart: true } do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.file_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'form' %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leagues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Logo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.title %></td>
        <td><%= league.logo %></td>
        <td><%= link_to 'Show', league %></td>
        <td><%= link_to 'Edit', edit_league_path(league) %></td>
        <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>New League</h1>

<%= render 'form' %>

<%= link_to 'Back', leagues_path %>

app/views/leagues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @league.title %>
</p>

<p>
  <strong>Logo:</strong>
  <%= image_tag @league.logo_url %>
</p>

<%= link_to 'Edit', edit_league_path(@league) %> |
<%= link_to 'Back', leagues_path %>